[switches]
Hfcl-Switch ansible_host=192.168.180.96

[switches:vars]
ansible_user=admin
ansible_password=admin
ansible_connection=ssh
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
