"""
ansible_inventory.py
====================
Generates:
  1. ansible/inventory/hosts.ini
  2. ansible/inventory/group_vars/switches.yml
  3. config/layer2/vlan_access_access.yaml   ← thin shim for Ansible playbook vars_files
     (regenerated from lab_config.yaml every run — never edit directly)
"""

import os
import sys
import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from lib.config_loader import cfg

ROOT          = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INVENTORY_DIR = os.path.join(ROOT, 'ansible', 'inventory')
HOSTS_FILE    = os.path.join(INVENTORY_DIR, 'hosts.ini')
GROUP_VARS    = os.path.join(INVENTORY_DIR, 'group_vars', 'switches.yml')
SHIM_DIR      = os.path.join(ROOT, 'config', 'layer2')
SHIM_FILE     = os.path.join(SHIM_DIR, 'vlan_access_access.yaml')


def generate():
    os.makedirs(os.path.join(INVENTORY_DIR, 'group_vars'), exist_ok=True)
    os.makedirs(SHIM_DIR, exist_ok=True)

    devices = cfg['devices']
    first   = next(iter(devices.values()))

    # ── 1. hosts.ini ────────────────────────────────────────────────────────
    lines = [
        "# AUTO-GENERATED by lib/ansible_inventory.py — DO NOT EDIT",
        "# Source: config/lab_config.yaml",
        "",
        "[switches]",
    ]
    for name, d in devices.items():
        lines.append(
            f"{name} ansible_host={d['host']} "
            f"ansible_user={d['username']} "
            f"ansible_password={d['password']} "
            f"ansible_connection=network_cli "
            f"ansible_network_os=ios"
        )
    lines += ["", "[all:vars]", "ansible_ssh_common_args='-o StrictHostKeyChecking=no'", ""]

    with open(HOSTS_FILE, 'w') as f:
        f.write('\n'.join(lines))
    print(f"  [OK] {HOSTS_FILE}")

    # ── 2. group_vars/switches.yml ──────────────────────────────────────────
    if os.path.exists(GROUP_VARS):
        os.chmod(GROUP_VARS, 0o644)
    with open(GROUP_VARS, 'w') as f:
        f.write("# AUTO-GENERATED — source: config/lab_config.yaml — DO NOT EDIT\n")
        yaml.dump({
            'ansible_user':       first['username'],
            'ansible_password':   first['password'],
            'ansible_connection': 'network_cli',
            'ansible_network_os': 'ios',
        }, f, default_flow_style=False)
    print(f"  [OK] {GROUP_VARS}")

    # ── 3. config/layer2/vlan_access_access.yaml (shim for vars_files) ─────
    t   = cfg['traffic']
    ifs = cfg['interfaces']['HFCL']
    shim = {
        # Device
        'switch_name': 'HFCL',
        'switch_ip':   first['host'],
        'switch_user': first['username'],
        'switch_pass': first['password'],
        # VLAN
        'vlan_id':   cfg['vlans']['test_vlan_1'],
        'vlan_name': 'TEST_VLAN',
        # Interfaces — use exact names from lab_config
        'access_port1': ifs['access_port_1'],
        'access_port2': ifs['access_port_2'],
        # Traffic hosts
        'sender_host':       f"{t['sender']['user']}@{t['sender']['host']}",
        'receiver_host':     f"{t['receiver']['user']}@{t['receiver']['host']}",
        'traffic_interface': t['sender']['interface'],
        'traffic_timeout':   t['timeout'],
        'packet_count':      t['packet_count'],
        'packet_interval':   t['packet_interval'],
        # Report paths
        'sender_report':    cfg['reports']['sender_json'],
        'receiver_report':  cfg['reports']['receiver_json'],
        'execution_report': '/tmp/vlan_access_access_report.txt',
    }
    with open(SHIM_FILE, 'w') as f:
        f.write("# AUTO-GENERATED from config/lab_config.yaml — DO NOT EDIT\n")
        yaml.dump(shim, f, default_flow_style=False, sort_keys=False)
    print(f"  [OK] {SHIM_FILE}")


if __name__ == '__main__':
    print("Generating Ansible inventory from lab_config.yaml ...")
    generate()
    print("Done.")
